# Generated by Django 5.1.1 on 2024-09-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('climate', models.CharField(max_length=100)),
                ('safety_score', models.IntegerField()),
                ('cost_of_living', models.IntegerField()),
                ('budget_score', models.IntegerField()),
                ('visa_ease', models.CharField(max_length=100)),
                ('air_quality', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
