# Generated by Django 5.1.1 on 2024-10-01 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('continent', models.CharField(max_length=50)),
                ('climate', models.CharField(blank=True, max_length=50, null=True)),
                ('safety_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cost_of_living', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('budget_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('visa_ease', models.CharField(blank=True, max_length=50, null=True)),
                ('air_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('internet_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
