# Generated by Django 5.1.1 on 2024-10-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_search_api_search_preferr_7f53d7_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='loq_humidity',
            new_name='low_humidity',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='only_monitoring_Stations',
            new_name='only_monitoring_stations',
        ),
    ]
