# Generated by Django 5.1.1 on 2024-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_loq_humidity_search_low_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='continent',
            field=models.CharField(blank=True, choices=[('ANY', 'ANY'), ('AF', 'Africa'), ('AN', 'Antartica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=3, null=True),
        ),
    ]
