# Generated by Django 5.1.1 on 2024-10-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_search_continent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='cities',
        ),
    ]
