# Generated by Django 5.1.1 on 2025-06-02 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('continent', models.CharField(blank=True, choices=[('ANY', 'ANY'), ('AF', 'Africa'), ('AN', 'Antartica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=3, null=True)),
                ('min_temp', models.IntegerField(blank=True, null=True)),
                ('max_temp', models.IntegerField(blank=True, null=True)),
                ('preferred_humidity', models.CharField(choices=[('ANY', 'Any'), ('DRY', 'Dry'), ('MOD', 'Moderate'), ('HUM', 'Humid')], default='ANY', max_length=3)),
                ('sunny', models.BooleanField(default=False)),
                ('rainy', models.BooleanField(default=False)),
                ('snowy', models.BooleanField(default=False)),
                ('windy', models.BooleanField(default=False)),
                ('visa_type', models.CharField(choices=[('ANY', 'Any'), ('Tourist', 'Tourist Visa'), ('work', 'Work Visa'), ('student', 'Student Visa'), ('digital nomad', 'Digital Nomad Visa')], default='ANY', max_length=20)),
                ('max_stay_duration', models.CharField(choices=[('ANY', 'Any'), ('30D', '30 Days'), ('90D', '90 Days'), ('180D', '180 Days'), ('1Y', '1 Year'), ('1Y+', '1+ Years')], default='ANY', max_length=4)),
                ('visa_on_arrival', models.BooleanField(default=False)),
                ('no_visa_required', models.BooleanField(default=False)),
                ('e_visa_available', models.BooleanField(default=False)),
                ('embassy_application', models.BooleanField(default=False)),
                ('max_processing_time', models.PositiveIntegerField(blank=True, null=True)),
                ('safety_rating', models.CharField(choices=[('ANY', 'Any'), ('V_HIGH', 'Very High'), ('HIGH', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='ANY', max_length=7)),
                ('crime_concerns', models.BooleanField(default=False)),
                ('political_concerns', models.BooleanField(default=False)),
                ('natural_disaster_concerns', models.BooleanField(default=False)),
                ('health_concerns', models.BooleanField(default=False)),
                ('lgbtq_friendly', models.BooleanField(default=False)),
                ('solo_friendly', models.BooleanField(default=False)),
                ('travel_advisory', models.CharField(choices=[('ANY', 'Any'), ('NW', 'No warnings'), ('ECN', 'Exercise caution'), ('RT', 'Reconsider travel'), ('DNT', 'Do not travel')], default='ANY', max_length=3)),
                ('cost_of_living_index', models.CharField(choices=[('ANY', 'Any'), ('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='ANY', max_length=4)),
                ('budget_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wifi_amenities', models.BooleanField(default=False)),
                ('workspaces', models.BooleanField(default=False)),
                ('kitchen_amenities', models.BooleanField(default=False)),
                ('laundry_amenities', models.BooleanField(default=False)),
                ('air_quality_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('low_allergen', models.BooleanField(default=False)),
                ('clean_indoor_air', models.BooleanField(default=False)),
                ('low_humidity', models.BooleanField(default=False)),
                ('low_pollution', models.BooleanField(default=False)),
                ('only_monitoring_stations', models.BooleanField(default=False)),
                ('internet_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('include_5G', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='search_sear_user_id_007d77_idx'), models.Index(fields=['continent'], name='search_sear_contine_22056d_idx'), models.Index(fields=['min_temp'], name='search_sear_min_tem_15bd16_idx'), models.Index(fields=['budget_score'], name='search_sear_budget__a266f5_idx'), models.Index(fields=['visa_type'], name='search_sear_visa_ty_f559ab_idx'), models.Index(fields=['safety_rating'], name='search_sear_safety__18828d_idx'), models.Index(fields=['cost_of_living_index'], name='search_sear_cost_of_52dc2e_idx'), models.Index(fields=['air_quality_index'], name='search_sear_air_qua_e15b2c_idx'), models.Index(fields=['internet_quality'], name='search_sear_interne_9de20a_idx'), models.Index(fields=['preferred_humidity'], name='search_sear_preferr_37e80f_idx')],
            },
        ),
    ]
